version: 2
jobs:
  build:
    docker:
    - image: node:8.10.0

    working_directory: ~/repo

    steps:
    - checkout

    - run:
        command: |
          npm install -g zapier-platform-cli
          npm install
          zapier test



workflows:
  version: 2
  build:
    jobs:
    - build